### ISSUE TITLE
Newbie question: what lib to include for OTA?

### ISSUE THREAD

**Issue by andig** [pgollor/esp8266-webconf-mDNS-OTA#4]
I've setup Arduino 1.65 plus the staging esp8266 core to get FS support. Compile now gest stuck on OTA:

```
fatal error: ArduinoOTA.h: No such file or directory
```

Could not find such lib. Could you give a hint?

Btw, much appreciated, exactly what I was looking for as basis for wireless energy monitoring sensor to attach to http://volkszaehler.org

**Update** just saw https://github.com/pgollor/esp8266-webconf-mDNS-OTA/issues/1 so I need to move to git instead of staging?

**Comment by pgollor** [comment]
Sorry you have to use the current master branch from [Arduino ESP](https://github.com/esp8266/Arduino)

**Comment by andig** [comment]
Good to know, thank you!
